// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Model;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(MemberContext))]
    [Migration("20190721175307_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Model.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AltNumber");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("EmailConfirm")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<bool>("IsFridayChecked");

                    b.Property<bool>("IsMondayChecked");

                    b.Property<bool>("IsSaturdayChecked");

                    b.Property<bool>("IsSundayChecked");

                    b.Property<bool>("IsThursdayChecked");

                    b.Property<bool>("IsTuesdayChecked");

                    b.Property<bool>("IsWednesdayChecked");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<string>("Street")
                        .IsRequired();

                    b.Property<string>("Town")
                        .IsRequired();

                    b.HasKey("MemberID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("WebApplication1.Model.SurfAlert", b =>
                {
                    b.Property<int>("SurfAlertID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<decimal>("MaxSwellHeight");

                    b.Property<int>("MaxWind");

                    b.Property<int>("MemberID");

                    b.Property<int>("MinPeriod");

                    b.Property<decimal>("MinSwellHeight");

                    b.Property<string>("WindDirection")
                        .IsRequired();

                    b.HasKey("SurfAlertID");

                    b.ToTable("SurfAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
