// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurfProject.Model;

namespace SurfProject.Migrations
{
    [DbContext(typeof(MemberDetailsContext))]
    [Migration("20190729101045_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SurfProject.Model.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AltNumber");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("EmailConfirm")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<string>("Street")
                        .IsRequired();

                    b.Property<string>("Town")
                        .IsRequired();

                    b.HasKey("MemberID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("SurfProject.Model.SurfProfile", b =>
                {
                    b.Property<int>("SurfProfileID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsFridayChecked");

                    b.Property<bool>("IsMondayChecked");

                    b.Property<bool>("IsSaturdayChecked");

                    b.Property<bool>("IsSundayChecked");

                    b.Property<bool>("IsThursdayChecked");

                    b.Property<bool>("IsTuesdayChecked");

                    b.Property<bool>("IsWednesdayChecked");

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<decimal>("MaxSwellHeight");

                    b.Property<int>("MemberID");

                    b.Property<int>("MinPeriod");

                    b.Property<decimal>("MinSwellHeight");

                    b.Property<string>("SwellDirection")
                        .IsRequired();

                    b.Property<string>("WindDirection")
                        .IsRequired();

                    b.Property<int>("WindStrength");

                    b.HasKey("SurfProfileID");

                    b.ToTable("dbo.WaveConditions");
                });
#pragma warning restore 612, 618
        }
    }
}
